schema_version = 1

[[repositories]]
name = "burn_ecs"
path = "../burn_ecs"
url = "https://github.com/aberration-technology/burn_ecs.git"
revision = "b4ab09125838ccb81925102e2a2ce20d7f95d659"

[[repositories]]
name = "burn_p2p"
path = "../burn_p2p"
url = "https://github.com/aberration-technology/burn_p2p.git"
revision = "6d8f5400b171fafe0f20550f51eb79db3d84c4bf"

[[repositories]]
name = "burn_eggroll"
path = "../burn_eggroll"
url = "https://github.com/aberration-technology/burn_eggroll.git"
revision = "56fffb50af0c0a7bd1df81c38709a150c9755c39"

[[repositories]]
name = "burn_pc"
path = "../burn_pc"
url = "https://github.com/aberration-technology/burn_pc.git"
revision = "282e8c3f601f63abf6e202b42039e8b3f6434c4f"
