schema_version = 1

[[repositories]]
name = "burn_ecs"
path = "../burn_ecs"
url = "https://github.com/aberration-technology/burn_ecs.git"
revision = "115cdfe8cd4212c529ab11be1f38887abf558ba0"

[[repositories]]
name = "burn_p2p"
path = "../burn_p2p"
url = "https://github.com/aberration-technology/burn_p2p.git"
revision = "6d8f5400b171fafe0f20550f51eb79db3d84c4bf"

[[repositories]]
name = "burn_eggroll"
path = "../burn_eggroll"
url = "https://github.com/aberration-technology/burn_eggroll.git"
revision = "bc11f547c1096da0c662ddf9e2fa1fb7f8c3f6bc"

[[repositories]]
name = "burn_pc"
path = "../burn_pc"
url = "https://github.com/aberration-technology/burn_pc.git"
revision = "2aaab500cce6fa04ecdda4ba5c7667b9ce07d035"
