#!/usr/bin/env bash
set -euo pipefail

: "${GH_TOKEN:?GH_TOKEN must be set}"
: "${BURN_DRAGON_NATIVE_CANARY_ENVIRONMENT:?BURN_DRAGON_NATIVE_CANARY_ENVIRONMENT must be set}"
: "${BURN_DRAGON_NATIVE_CANARY_EDGE_BASE_URL:?BURN_DRAGON_NATIVE_CANARY_EDGE_BASE_URL must be set}"
: "${BURN_DRAGON_NATIVE_CANARY_EXPERIMENT_KIND:?BURN_DRAGON_NATIVE_CANARY_EXPERIMENT_KIND must be set}"
: "${BURN_DRAGON_NATIVE_CANARY_EXPERIMENT_ID:?BURN_DRAGON_NATIVE_CANARY_EXPERIMENT_ID must be set}"
: "${BURN_DRAGON_NATIVE_CANARY_BACKEND:?BURN_DRAGON_NATIVE_CANARY_BACKEND must be set}"
: "${BURN_DRAGON_NATIVE_CANARY_PRINCIPAL_ID:?BURN_DRAGON_NATIVE_CANARY_PRINCIPAL_ID must be set}"
: "${BURN_DRAGON_NATIVE_CANARY_WINDOWS:?BURN_DRAGON_NATIVE_CANARY_WINDOWS must be set}"
: "${BURN_DRAGON_NATIVE_CANARY_SETTLE_DIFFUSION:=true}"
: "${BURN_DRAGON_NATIVE_CANARY_DIFFUSION_SETTLE_PASSES:=2}"
: "${BURN_DRAGON_NATIVE_CANARY_SERVE_AFTER_PUBLISH_SECS:=45}"
: "${BURN_DRAGON_NATIVE_CANARY_COMMAND_TIMEOUT_SECS:=900}"
: "${BURN_DRAGON_NATIVE_CANARY_START_VALIDATOR:=false}"
: "${BURN_DRAGON_NATIVE_CANARY_TRAINING_BATCH_SIZE:=1}"
: "${BURN_DRAGON_NATIVE_CANARY_TRAINING_MAX_ITERS:=2}"
: "${BURN_DRAGON_NATIVE_CANARY_EVALUATION_MAX_BATCHES:=1}"
: "${BURN_DRAGON_NATIVE_CANARY_REQUIRE_CANONICAL_LOSS_NON_REGRESSION:=false}"
: "${BURN_DRAGON_NATIVE_CANARY_WATCH_INTERVAL_SECS:=60}"

python3 scripts/agent_task.py gh-dispatch \
  --repo "${GITHUB_REPOSITORY}" \
  --workflow .github/workflows/live-native-training-canary.yml \
  --ref "${GITHUB_REF_NAME}" \
  --label live-native-training-canary \
  --input environment="${BURN_DRAGON_NATIVE_CANARY_ENVIRONMENT}" \
  --input edge_base_url="${BURN_DRAGON_NATIVE_CANARY_EDGE_BASE_URL}" \
  --input experiment_kind="${BURN_DRAGON_NATIVE_CANARY_EXPERIMENT_KIND}" \
  --input experiment_id="${BURN_DRAGON_NATIVE_CANARY_EXPERIMENT_ID}" \
  --input backend="${BURN_DRAGON_NATIVE_CANARY_BACKEND}" \
  --input principal_id="${BURN_DRAGON_NATIVE_CANARY_PRINCIPAL_ID}" \
  --input windows="${BURN_DRAGON_NATIVE_CANARY_WINDOWS}" \
  --input settle_diffusion="${BURN_DRAGON_NATIVE_CANARY_SETTLE_DIFFUSION}" \
  --input diffusion_settle_passes="${BURN_DRAGON_NATIVE_CANARY_DIFFUSION_SETTLE_PASSES}" \
  --input serve_after_publish_secs="${BURN_DRAGON_NATIVE_CANARY_SERVE_AFTER_PUBLISH_SECS}" \
  --input command_timeout_secs="${BURN_DRAGON_NATIVE_CANARY_COMMAND_TIMEOUT_SECS}" \
  --input start_validator="${BURN_DRAGON_NATIVE_CANARY_START_VALIDATOR}" \
  --input training_batch_size="${BURN_DRAGON_NATIVE_CANARY_TRAINING_BATCH_SIZE}" \
  --input training_max_iters="${BURN_DRAGON_NATIVE_CANARY_TRAINING_MAX_ITERS}" \
  --input evaluation_max_batches="${BURN_DRAGON_NATIVE_CANARY_EVALUATION_MAX_BATCHES}" \
  --input require_canonical_loss_non_regression="${BURN_DRAGON_NATIVE_CANARY_REQUIRE_CANONICAL_LOSS_NON_REGRESSION}" \
  --wait \
  --interval-secs "${BURN_DRAGON_NATIVE_CANARY_WATCH_INTERVAL_SECS}" \
  --exit-status
