#!/usr/bin/env bash
set -euo pipefail

: "${BURN_DRAGON_BROWSER_CANARY_SITE_BASE_URL:?BURN_DRAGON_BROWSER_CANARY_SITE_BASE_URL must be set}"
: "${BURN_DRAGON_BROWSER_CANARY_EDGE_BASE_URL:?BURN_DRAGON_BROWSER_CANARY_EDGE_BASE_URL must be set}"
: "${BURN_DRAGON_BROWSER_CANARY_PRINCIPAL_ID:?BURN_DRAGON_BROWSER_CANARY_PRINCIPAL_ID must be set}"
: "${BURN_DRAGON_BROWSER_CANARY_CALLBACK_TOKEN:?BURN_DRAGON_BROWSER_CANARY_CALLBACK_TOKEN must be set}"
: "${BURN_DRAGON_BROWSER_CANARY_EXPERIMENT_ID:?BURN_DRAGON_BROWSER_CANARY_EXPERIMENT_ID must be set}"

site_dir="${BURN_DRAGON_PAGES_PREDEPLOY_SITE_DIR:-target/browser-site}"
if [ ! -f "${site_dir}/browser-app-config.json" ] || [ ! -f "${site_dir}/burn_dragon_p2p_browser_bg.wasm" ]; then
  echo "predeploy browser canary requires a built browser site in ${site_dir}" >&2
  exit 1
fi

export PLAYWRIGHT_BROWSERS="${PLAYWRIGHT_BROWSERS:-chromium}"
export BURN_DRAGON_BROWSER_CANARY_BROWSER="${BURN_DRAGON_BROWSER_CANARY_BROWSER:-chromium}"
export BURN_DRAGON_BROWSER_CANARY_TRANSPORT_MODE="${BURN_DRAGON_BROWSER_CANARY_TRANSPORT_MODE:-webrtc-direct}"
export BURN_DRAGON_BROWSER_CANARY_EXPECT_TRAINING="${BURN_DRAGON_BROWSER_CANARY_EXPECT_TRAINING:-1}"
export BURN_DRAGON_BROWSER_CANARY_EXPECT_CHECKPOINT_SYNC="${BURN_DRAGON_BROWSER_CANARY_EXPECT_CHECKPOINT_SYNC:-0}"
export BURN_DRAGON_BROWSER_CANARY_MIN_ACCEPTED_RECEIPTS="${BURN_DRAGON_BROWSER_CANARY_MIN_ACCEPTED_RECEIPTS:-2}"
export BURN_DRAGON_BROWSER_CANARY_SITE_OVERRIDE_DIR="$site_dir"
export BURN_DRAGON_BROWSER_CANARY_ARTIFACT_DIR="${BURN_DRAGON_BROWSER_CANARY_ARTIFACT_DIR:-${RUNNER_TEMP:-/tmp}/burn-dragon-pages-predeploy-canary}"
export BURN_DRAGON_BROWSER_CANARY_OUTPUT_JSON="${BURN_DRAGON_BROWSER_CANARY_OUTPUT_JSON:-${BURN_DRAGON_BROWSER_CANARY_ARTIFACT_DIR}/canary-summary.json}"

bash scripts/install_playwright_chromium.sh
bash scripts/run_live_browser_canary.sh
