from pathlib import Path


def main() -> None:
    script = Path("scripts/live-browser-canary.mjs").read_text()
    required_snippets = [
        "function browserConfigSeedNodeUrls(browserConfig)",
        "function browserConfigTrainingConfig(browserConfig)",
        "function summarizeBrowserTrainingProfile(browserConfig)",
        "function applyBrowserTrainingCanaryProfile(browserConfig)",
        "training.max_train_batches = 1;",
        "training.max_eval_batches = 0;",
        "training.live_participant.publish_canonical_update = false;",
        "training.live_participant.load_active_head_artifact = false;",
        "training.model_config.n_embd = 16;",
        'training.model_config.language_head = { type: "standard_token_classification" };',
        "browserConfig.config?.network?.seed_node_urls",
        "browserConfig.config?.training",
        "browserConfig.seed_node_urls",
        "function snapshotAllowsBrowserTraining(snapshot, experimentId)",
        "const browserConfigSeeds = browserConfigSeedNodeUrls(filteredBrowserConfig);",
        "const browserTrainingConfig = browserConfigTrainingConfig(filteredBrowserConfig);",
        "!snapshotAllowsBrowserTraining(snapshot, EXPERIMENT_ID)",
        'browser config and live snapshot are missing browser training for selected experiment ${EXPERIMENT_ID}',
        'const PENDING_GITHUB_LOGIN_KEY = "burn-dragon-p2p.pending-github-login";',
        'const TRUSTED_CALLBACK_TOKEN_KEY = "burn-dragon-p2p.canary-callback-token";',
        "const callbackUrl = endpoint(SITE_BASE_URL, `${provider.callback_path}?code=browser-canary-provider-code`);",
        "window.sessionStorage.setItem(trustedCallbackTokenKey, callbackToken);",
        'document.body.innerText.includes("Browser training complete:")',
        'document.body.innerText.includes("Browser training window")',
        'report.training_button_label === "stop training"',
        "async function beginBrowserCanaryLogin(snapshot) {",
        'const BROWSER_NAME = (',
        'const TRANSPORT_MODE = (',
        'const EXPECT_TRAINING = parseBooleanEnv("BURN_DRAGON_BROWSER_CANARY_EXPECT_TRAINING", true);',
        'const EXPECT_CHECKPOINT_SYNC = parseBooleanEnv(',
        '"BURN_DRAGON_BROWSER_CANARY_EXPECT_CHECKPOINT_SYNC"',
        "function machineStateCheckpointReady(report)",
        "function normalizeArtifactSourceLabel(value)",
        "browser canary did not sync active head checkpoint over P2P",
        "browser checkpoint canary used edge artifact fallback instead of P2P",
        "training_p2p_checkpoint_ready: null",
        "report.training_p2p_checkpoint_ready = machineStateCheckpointReady(report);",
        "browser training canary did not sync the active head checkpoint over P2P before training",
        "expect_checkpoint_sync: EXPECT_CHECKPOINT_SYNC",
        "function filterSignedSeedAdvertisementForTransport(envelope, mode)",
        "function preferValidatedSignedSeedAdvertisement(envelope, mode)",
        'payload.transport_policy = { preferred: ["WebRtcDirect"], allow_fallback_wss: false };',
        "function filterBrowserConfigForTransport(browserConfig, mode)",
        "const DIALABLE_WEBRTC_HOST_PROTOCOLS = new Set([",
        '"dns",',
        "DIALABLE_WEBRTC_HOST_PROTOCOLS.has(segments[0])",
        'import { isIP } from "node:net";',
        "function canonicalBrowserSeedUrl(edgeBaseUrl, seed)",
        "function canonicalBrowserSeedUrls(edgeBaseUrl, seeds)",
        "const canonicalSignedSeeds = canonicalBrowserSeedUrls(EDGE_BASE_URL, signedSeeds);",
        "const canonicalBrowserConfigSeeds = canonicalBrowserSeedUrls(EDGE_BASE_URL, browserConfigSeeds);",
        "const productionBrowserTrainingConfig = browserConfigTrainingConfig(",
        "production browser training is not configured to publish canonical updates",
        "production browser training is not configured to load the active head artifact",
        "production_training_profile: summarizeBrowserTrainingProfile(transportFilteredBrowserConfig)",
        "training_canary_profile: summarizeBrowserTrainingProfile(filteredBrowserConfig)",
        "canonical_config=${JSON.stringify(canonicalBrowserConfigSeeds)}",
        "function reportConnectedForMode(report, mode)",
        "return transportConnectedForMode(report.transport_summary, mode);",
        "function labeledRowsValue(rows, label)",
        '".dragon-metrics-grid .dragon-metric"',
        '".dragon-live-keyvalues .keyvalue-row"',
        '".dragon-live-machine-state, .dragon-machine-state"',
        "WEBRTC_DIRECT_REQUIRED_CONSOLE_MARKERS",
        "libp2p webrtc-direct: completed Noise handshake peer=",
        "function assertWebRtcDirectTransportPhases(report, consoleMessages)",
        "browser canary connected without complete WebRTC-direct phase evidence",
        "report.webrtc_direct_console_markers = webRtcDirectConsoleMarkerReport(consoleMessages);",
        "retained_transport_error: null",
        "report.page_errors = uniqueStrings(pageErrors);",
        "report.console_errors = uniqueStrings(",
        "function uniqueStrings(values)",
        "report.retained_transport_error = reportConnectedForMode(report, TRANSPORT_MODE)",
        "? null",
        ": (report.browser_machine_state?.last_error ?? null);",
        "BURN_DRAGON_BROWSER_CANARY_DURABLE_RECEIPT_TIMEOUT_MS",
        "BURN_DRAGON_BROWSER_CANARY_MIN_ACCEPTED_RECEIPTS",
        "function waitForAcceptedReceiptSubmissions(page, minimumAcceptedReceipts, timeoutMs)",
        "timed out waiting for ${minimumAcceptedReceipts} accepted browser receipts",
        "minimum_browser_receipts_accepted",
        "accepted_receipts_reached_durable_edge_state",
        "function buildBrowserE2eContract(report)",
        "function assertBrowserE2eContract(report)",
        "browser e2e contract failed",
        "e2e_contract: null",
        "function snapshotAcceptedReceiptCount(snapshot)",
        "function acceptedReceiptIdsFromSubmission(body)",
        "async function waitForDurableReceiptCount(acceptedReceiptIds, baselineCount)",
        "browser receipt was accepted but did not become durable edge state",
        "accepted_receipts_before_training: acceptedReceiptsBeforeTraining",
        "durable_receipt_snapshot: null",
        "min_accepted_receipts: MIN_ACCEPTED_RECEIPTS",
        "accepted_receipt_ids: acceptedReceiptIds",
        "accepted_receipt_count: acceptedReceiptIds.length",
        "report.durable_receipt_snapshot = await waitForDurableReceiptCount(",
    ]
    for snippet in required_snippets:
        assert snippet in script, f"live-browser-canary.mjs missing required snippet: {snippet}"
    forbidden_snippets = [
        'const session = await fetchJson(endpoint(EDGE_BASE_URL, callbackPath)',
        'const certificate = await fetchJson(endpoint(EDGE_BASE_URL, snapshot.paths.enroll_path)',
        "SELECTED_EXPERIMENT_ID",
        "/release-manifest.json",
        "browser canary retained a direct transport error after connect",
    ]
    for snippet in forbidden_snippets:
        assert snippet not in script, (
            f"live-browser-canary.mjs should not pre-consume browser callback flow: {snippet}"
        )
    print("live-browser-canary-script-ok")


if __name__ == "__main__":
    main()
